name: Notifier
api: [1.0.0,2.0.0]
main: Jankirby\Notifier\Main
version: 1.0
load: POSTWORLD
description: Notify your server operators!

command:
cmd1:
  description: Notifier About
  
  permissions:
    notifier.about:
    default: true
